# Generated by Django 2.0.3 on 2018-06-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='chsCode',
            field=models.CharField(max_length=9, null=True, verbose_name='赛事代码'),
        ),
    ]
