# Generated by Django 2.0.3 on 2018-06-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0002_auto_20180603_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='techStastics',
            field=models.FileField(null=True, upload_to='E:/gfile/Match'),
        ),
        migrations.AlterField(
            model_name='team',
            name='playerList',
            field=models.FileField(null=True, upload_to='E:/gfile/Team/player_lists'),
        ),
    ]
