# Generated by Django 2.0.3 on 2018-06-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0002_auto_20180601_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='chsName',
            field=models.CharField(max_length=64, null=True, verbose_name='赛事名称'),
        ),
    ]
