# Generated by Django 2.0.3 on 2018-06-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0003_championship_chsname'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='endTime',
            field=models.DateField(null=True, verbose_name='结束日期'),
        ),
        migrations.AddField(
            model_name='championship',
            name='startTime',
            field=models.DateField(null=True, verbose_name='开始日期'),
        ),
    ]
