# Generated by Django 2.0.3 on 2018-06-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0003_auto_20180603_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='playerStatistics',
            field=models.FileField(null=True, upload_to='E:/gifle/Team/player_statistics'),
        ),
    ]
