# Generated by Django 2.0.3 on 2018-06-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0004_team_playerstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='techStastics',
            field=models.FileField(null=True, upload_to='gfile/Match'),
        ),
        migrations.AlterField(
            model_name='team',
            name='playerList',
            field=models.FileField(null=True, upload_to='gfile/Team/player_lists'),
        ),
        migrations.AlterField(
            model_name='team',
            name='playerStatistics',
            field=models.FileField(null=True, upload_to='gifle/Team/player_statistics'),
        ),
    ]
