# Generated by Django 2.0.3 on 2018-06-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0005_auto_20180605_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='rank_for_cup',
            field=models.FileField(null=True, upload_to='Championship/cup'),
        ),
        migrations.AddField(
            model_name='championship',
            name='rank_for_league',
            field=models.FileField(null=True, upload_to='Championship/league'),
        ),
        migrations.AlterField(
            model_name='match',
            name='techStastics',
            field=models.FileField(null=True, upload_to='Match'),
        ),
        migrations.AlterField(
            model_name='team',
            name='playerList',
            field=models.FileField(null=True, upload_to='Team/player_lists'),
        ),
        migrations.AlterField(
            model_name='team',
            name='playerStatistics',
            field=models.FileField(null=True, upload_to='Team/player_statistics'),
        ),
    ]
