# Generated by Django 2.0.3 on 2018-06-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0006_auto_20180605_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='timetable',
            field=models.FileField(null=True, upload_to='Championship/timetable'),
        ),
    ]
