# Generated by Django 2.0.3 on 2018-06-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0007_championship_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='team_list',
            field=models.TextField(null=True),
        ),
    ]
