# Generated by Django 2.0.3 on 2018-06-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleID', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
            ],
        ),
    ]
