# Generated by Django 2.0.3 on 2018-06-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleID',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
