# Generated by Django 2.0.3 on 2018-06-02 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orgnisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgID', models.CharField(max_length=16, verbose_name='组织代码')),
                ('orgName', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('orgType', models.CharField(choices=[('club', '俱乐部'), ('association', '组织方'), ('group', '民间团体')], max_length=16, verbose_name='组织类型')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regionID', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='地区代码')),
                ('province', models.CharField(max_length=32, verbose_name='省份')),
                ('city', models.CharField(max_length=32, verbose_name='城市')),
                ('district', models.CharField(max_length=32, null=True, verbose_name='县市区')),
            ],
        ),
        migrations.AddField(
            model_name='orgnisation',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgnisation.Region', verbose_name='组织地区'),
        ),
    ]
