# Generated by Django 2.0.3 on 2018-06-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgnisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgnisation',
            name='orgID',
            field=models.CharField(max_length=16, verbose_name='组织代码'),
        ),
    ]
